#!/usr/bin/env python3
"""Merge the SEEE daily panel with ccn.ac.cn fills into one daily series,
and validate the fills against SEEE cumulative-volume deltas and monthly
bulletins.

Outputs:
  carbon/data/cea_daily_merged.csv   one row per trading day, provenance-tagged
  carbon/data/cea_validation_report.md

Merge rules:
  - Where a SEEE daily bulletin exists, it is authoritative (source=seee).
  - Where only ccn has the day (SEEE year archives list ~150 newest/year, so
    Jan..May of 2023/2024/2025 are truncated), aggregate ccn vintages
    (source=ccn). OHLC on vintage-split days refers to the max-volume vintage
    (close_main_vintage names it); pre-split days are the single CEA book.
  - 2022-01-04 .. 2022-05-25 has no public daily source (SEEE truncation +
    aggregators start later): daily rows absent; see cea_weekly.csv bridge.
"""
import csv
import os
from collections import defaultdict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(REPO, "carbon", "data")

COLS = [
    "trade_date", "source", "price_basis", "open", "high", "low", "close",
    "close_vintage", "listed_vol_t", "listed_amt_cny", "listed_vwap",
    "block_vol_t", "block_amt_cny", "block_vwap",
    "auction_vol_t", "auction_amt_cny",
    "total_vol_t", "total_amt_cny", "total_vwap", "cum_vol_t", "cum_amt_cny",
]


def fnum(x):
    return float(x) if x not in (None, "") else None


def main():
    seee = {r["trade_date"]: r for r in csv.DictReader(open(os.path.join(DATA, "cea_daily.csv")))}
    ccn_by_day = defaultdict(list)
    for r in csv.DictReader(open(os.path.join(DATA, "cea_daily_by_vintage.csv"))):
        ccn_by_day[r["trade_date"]].append(r)

    merged = {}
    for d, r in seee.items():
        row = {c: r.get(c) for c in COLS if c in r}
        row["trade_date"], row["source"] = d, "seee"
        merged[d] = row
    for d, vrows in ccn_by_day.items():
        if d in merged:
            continue
        row = {"trade_date": d, "source": "ccn"}
        tot = lambda c: sum(fnum(v[c]) or 0.0 for v in vrows)
        row["listed_vol_t"], row["listed_amt_cny"] = tot("listed_vol_t"), tot("listed_amt_cny")
        row["block_vol_t"], row["block_amt_cny"] = tot("block_vol_t"), tot("block_amt_cny")
        row["auction_vol_t"], row["auction_amt_cny"] = tot("auction_vol_t"), tot("auction_amt_cny")
        row["total_vol_t"], row["total_amt_cny"] = tot("total_vol_t"), tot("total_amt_cny")
        main_v = max(vrows, key=lambda v: fnum(v["total_vol_t"]) or 0.0)
        for c in ("open", "high", "low", "close"):
            row[c] = fnum(main_v[c])
        row["close_vintage"] = main_v["vintage"]
        row["price_basis"] = "listed" if d < "2023-08-28" else "composite"
        for leg, vol, amt in (("listed_vwap", "listed_vol_t", "listed_amt_cny"),
                              ("block_vwap", "block_vol_t", "block_amt_cny"),
                              ("total_vwap", "total_vol_t", "total_amt_cny")):
            row[leg] = round(row[amt] / row[vol], 4) if row[vol] else None
        merged[d] = row

    rows = [merged[d] for d in sorted(merged)]
    with open(os.path.join(DATA, "cea_daily_merged.csv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=COLS, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)

    # ---------- validation ----------
    lines = ["# CEA panel validation report", "",
             "Generated by pipeline/cea_merge.py. Sources: SEEE daily/weekly/monthly bulletins (authoritative), ccn.ac.cn monthly tables (fills + vintage detail).", ""]

    # 1. ccn fill windows vs SEEE cumulative deltas
    lines.append("## 1. Fill windows vs SEEE cumulative-volume deltas")
    seee_days = sorted(seee)
    gaps = []
    for a, b in zip(seee_days, seee_days[1:]):
        fill = [d for d in merged if a < d < b and merged[d]["source"] == "ccn"]
        if fill:
            gaps.append((a, b, sorted(fill)))
    for a, b, fill in gaps:
        cum_a, cum_b = fnum(seee[a]["cum_vol_t"]), fnum(seee[b]["cum_vol_t"])
        tot_b = fnum(seee[b]["total_vol_t"]) or 0.0
        fill_sum = sum(merged[d]["total_vol_t"] or 0.0 for d in fill)
        implied = (cum_b - cum_a) - tot_b if cum_a is not None and cum_b is not None else None
        ok = implied is not None and abs(implied - fill_sum) <= max(1.0, 0.0005 * implied)
        lines.append(f"- {a} -> {b}: {len(fill)} ccn fill days; ccn sum = {fill_sum:,.0f} t; "
                     f"SEEE cum-delta implies {implied:,.0f} t; {'MATCH' if ok else 'MISMATCH'}"
                     + (f" (diff {fill_sum - implied:,.0f} t, {abs(fill_sum-implied)/implied*100:.2f}%)" if implied else ""))

    # 2. ccn fill months vs monthly bulletins
    lines.append("")
    lines.append("## 2. Fill months vs SEEE monthly bulletins")
    monthly = {r["month"]: r for r in csv.DictReader(open(os.path.join(DATA, "cea_monthly.csv")))}
    by_month = defaultdict(float)
    n_days = defaultdict(int)
    for d, row in merged.items():
        if row["source"] == "ccn":
            by_month[d[:7]] += row["total_vol_t"] or 0.0
            n_days[d[:7]] += 1
    for ym in sorted(by_month):
        mrow = monthly.get(ym)
        seee_part = sum((fnum(r["total_vol_t"]) or 0.0) for d, r in seee.items() if d.startswith(ym))
        if mrow and fnum(mrow["total_vol_t"]) is not None:
            mv = fnum(mrow["total_vol_t"])
            combined = by_month[ym] + seee_part
            ok = abs(combined - mv) <= max(1.0, 0.001 * mv)
            lines.append(f"- {ym}: ccn({n_days[ym]}d)+seee = {combined:,.0f} t vs monthly bulletin {mv:,.0f} t; "
                         f"{'MATCH' if ok else 'MISMATCH'} (diff {combined - mv:,.0f} t)")
        else:
            lines.append(f"- {ym}: no monthly bulletin row to check")

    lines.append("")
    lines.append("Note on 2025-03: the +271,950 t excess is internally consistent inside the "
                 "ccn March 2025 table (per-day totals equal leg sums), i.e. some day(s) are "
                 "overstated as a whole; without an independent daily source for that window the "
                 "day cannot be pinpointed. Treat March 2025 ccn-fill volumes as approximate "
                 "(prices unaffected by this check); replace from Wind/CSMAR when available.")

    # 3. overlap day mismatches (ccn vs seee where both exist)
    lines.append("")
    lines.append("## 3. Days where ccn aggregates disagree with SEEE (SEEE kept)")
    n_overlap, bad = 0, []
    for d, vrows in ccn_by_day.items():
        if d not in seee or not seee[d]["total_vol_t"]:
            continue
        n_overlap += 1
        sv = fnum(seee[d]["total_vol_t"])
        cv = sum(fnum(v["total_vol_t"]) or 0.0 for v in vrows)
        if abs(sv - cv) > max(1.0, 0.001 * max(sv, cv)):
            bad.append((d, sv, cv))
    lines.append(f"{n_overlap} overlap days checked; {len(bad)} disagree (SEEE value kept in merged file):")
    for d, sv, cv in sorted(bad):
        lines.append(f"- {d}: seee {sv:,.0f} t vs ccn-sum {cv:,.0f} t")

    # 4. coverage summary
    lines.append("")
    lines.append("## 4. Coverage")
    years = defaultdict(lambda: [0, 0])
    for d, r in merged.items():
        years[d[:4]][0 if r["source"] == "seee" else 1] += 1
    for y in sorted(years):
        s, c = years[y]
        lines.append(f"- {y}: {s} seee days + {c} ccn fill days = {s + c}")
    lines.append("- Known daily hole: 2022-01-04 .. 2022-05-25 (no public daily source located; "
                 "weekly bridge in cea_weekly.csv; fill later via Wind/CSMAR if daily needed).")

    with open(os.path.join(DATA, "cea_validation_report.md"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"merged rows: {len(rows)} ({rows[0]['trade_date']} .. {rows[-1]['trade_date']})")
    print("report -> carbon/data/cea_validation_report.md")


if __name__ == "__main__":
    main()
